    analyze -library WORK -format sverilog "
                            $prj_path/ccs0201_defines/rtl/ccs0201_defines.v \
                            $prj_path/memss/rtl/pram.v \
                            $prj_path/memss/rtl/sram_wrap.v \
                            $prj_path/memss/rtl/sram_wrap_dp.v \
                            $prj_path/ahb_ic/rtl/ahb_ic.v \
                            $prj_path/uartm/rtl/uartm.v \
                            $prj_path/uartm/rtl/uartm_rx.v \
                            $prj_path/uartm/rtl/uartm_tx.v \
                            $prj_path/uartm/rtl/uartm_ahb.v \
                            $prj_path/gpcfg/rtl/gpcfg_rd.v \
                            $prj_path/gpcfg/rtl/gpcfg_rd_wr.v \
                            $prj_path/gpcfg/rtl/gpcfg_rd_wr_p.v \
                            $prj_path/gpcfg/rtl/gpcfg_rdata_mux.v \
                            $prj_path/gpcfg/rtl/hw_rng_fsm.v \
                            $prj_path/gpcfg/rtl/mod_exp.v \
                            $prj_path/gpcfg/rtl/gpcfg.v \
                            $prj_path/aes/rtl/aes128_table_ecb.v \
                            $prj_path/aes/rtl/AES_Comp.v \
                            $prj_path/aes_trust/rtl/Trojan_Trigger.v \
                            $prj_path/aes_trust/rtl/round.v \
                            $prj_path/aes_trust/rtl/table.v \
                            $prj_path/aes_trust/rtl/trust_top.v \
                            $prj_path/aes_trust/rtl/trust_aes_128.v \
                            $prj_path/aes_trust/rtl/trust_lfsr.v \
                            $prj_path/aes_trust/rtl/TSC.v \
                            $prj_path/intelregfile/rtl/intelregfile0.v \
                            $prj_path/intelregfile/rtl/intelregfile1.v \
                            $prj_path/intelregfile/rtl/intelregfile2.v \
                            $prj_path/intelregfile/rtl/intelregfile3.v \
                            $prj_path/intelregfile/rtl/intelregfile4.v \
                            $prj_path/intelregfile/rtl/sha256_core.v \
                            $prj_path/intelregfile/rtl/sha256_k_constants.v \
                            $prj_path/intelregfile/rtl/sha256_stream.v \
                            $prj_path/intelregfile/rtl/sha256_w_mem.v \
                            $prj_path/crypto_lib/rtl/montgomery_from_conv.v \
                            $prj_path/crypto_lib/rtl/montgomery_to_conv.v \
                            $prj_path/crypto_lib/rtl/trng.v \
                            $prj_path/crypto_lib/rtl/trng_wrap.v \
                            $prj_path/crypto_lib/rtl/vn_corrector.v \
                            $prj_path/crypto_lib/rtl/random_num_gen.v \
                            $prj_path/crypto_lib/rtl/montgomery_mul.v \
                            $prj_path/crypto_lib/rtl/mod_mul_il.v \
                            $prj_path/crypto_lib/rtl/bin_ext_gcd.v \
                            $prj_path/gpio/rtl/gpio.v \
                            $prj_path/timer/rtl/timer.v \
                            $prj_path/uarts/rtl/uarts_rx.v \
                            $prj_path/uarts/rtl/uarts_tx.v \
                            $prj_path/uarts/rtl/uarts.v \
                            $prj_path/chip_core/rtl/chip_core.v \
                            $prj_path/clk_ctl/rtl/clk_rst_ctl.v \
                            $prj_path/clk_ctl/rtl/gfm.v \
                            $prj_path/clk_ctl/rtl/clkdiv.v \
                            $prj_path/chiplib/rtl/chiplib.v \
                            $prj_path/$design/rtl/$design.v \
                            $prj_path/padring/rtl/padring.v"


